ALTER TABLE "hivemind"."OrgUsage"
  ADD COLUMN IF NOT EXISTS "taraSeconds" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "hyperAgentRuns" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "hivemind"."OrgUsageDaily"
  ADD COLUMN IF NOT EXISTS "taraSeconds" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "hyperAgentRuns" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "hivemind"."org_usage_cumulative"
  ADD COLUMN IF NOT EXISTS "tara_seconds" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "hyper_agent_runs" BIGINT NOT NULL DEFAULT 0;
