import test from 'node:test';
import assert from 'node:assert/strict';
import { checkNativeAiConsent,nativeAiProtectedPath,nativeBootstrapApiKey } from '../../src/mobile/consent-guard.js';
import { AI_DISCLOSURE_VERSION } from '../../src/mobile/privacy-routes.js';
import { handleMobileSafetyTriage } from '../../src/mobile/safety-triage.js';
test('native sharing guard denies absent, stale or withdrawn consent and storage failure',async()=>{for(const record of [null,{metadata:{granted:false,version:AI_DISCLOSURE_VERSION}},{metadata:{granted:true,version:'old'}}]){const result=await checkNativeAiConsent({auditLog:{findFirst:async q=>{assert.equal(q.where.userId,'user');return record;}}},{nativeMobile:true,userId:'user'});assert.equal(result.allowed,false);assert.equal(result.status,403);}assert.equal((await checkNativeAiConsent(null,{nativeMobile:true})).status,503);assert.equal((await checkNativeAiConsent({auditLog:{findFirst:async()=>{throw Error('db');}}},{nativeMobile:true})).status,503);});
test('grant permits native use; browser traffic unchanged',async()=>{assert.equal((await checkNativeAiConsent({auditLog:{findFirst:async()=>({metadata:{granted:true,version:AI_DISCLOSURE_VERSION}})}},{nativeMobile:true,userId:'user'})).allowed,true);assert.equal((await checkNativeAiConsent(null,{nativeMobile:false})).allowed,true);});
test('guarded AI namespaces include admission, proxy, voice and company research without blocking consent/profile',()=>{for(const path of ['/v1/harness-chat/bootstrap','/v1/proxy/chat','/v1/meetings/transcribe','/v1/hyper/company/analyze','/v1/research/run'])assert.equal(nativeAiProtectedPath(path,'POST'),true,path);for(const [path,method] of [['/v1/bootstrap','GET'],['/v1/mobile/privacy/ai-consent','POST'],['/v1/account','DELETE'],['/v1/proxy/health','GET'],['/v1/harness-chat/sessions/id','DELETE']])assert.equal(nativeAiProtectedPath(path,method),false,path);});
test('native bootstrap never calls broad key mint; browser path preserved',async()=>{let minted=0;const create=async()=>{minted++;return 'key';};assert.equal(await nativeBootstrapApiKey({nativeMobile:true},{id:'org'},create,'user'),null);assert.equal(minted,0);assert.equal(await nativeBootstrapApiKey({},null,create,'user'),null);assert.equal(await nativeBootstrapApiKey({}, {id:'org'},create,'user'),'key');assert.equal(minted,1);});
const reportId='11111111-1111-4111-8111-111111111111';
async function triage({method='GET',path='/admin/api/platform/mobile-safety-reports',operator={operator:'reviewer',sessionId:'22222222-2222-4222-8222-222222222222'},body={},db}={}){let status,data;await handleMobileSafetyTriage({req:{method},res:{},pathname:path,url:new URL(path,'https://admin.example.test'),prisma:db,getPlatformAdminSession:()=>operator,parseBody:async()=>body,jsonResponse:(_,d,s=200)=>{data=d;status=s;}});return{status,data};}
test('safety report inbox uses existing platform operator, not tenant admin or anonymous',async()=>{assert.equal((await triage({operator:null})).status,401);assert.equal((await triage()).status,503);});
test('safety status is appended audit record, never edits report; unknown report denied',async()=>{const writes=[];const db={auditLog:{findFirst:async q=>q.where.id===reportId?{id:reportId}:null,create:async q=>{writes.push(q.data);return{id:'receipt',createdAt:new Date(0)};}}};let response=await triage({method:'POST',path:`/admin/api/platform/mobile-safety-reports/${reportId}`,body:{status:'reviewing',note:'Inspecting generated answer'},db});assert.equal(response.status,201);assert.equal(writes[0].resourceId,reportId);assert.equal(writes[0].actorType,'platform_admin');assert.equal(writes[0].eventType,'mobile.ai_safety_triage');response=await triage({method:'POST',path:'/admin/api/platform/mobile-safety-reports/33333333-3333-4333-8333-333333333333',body:{status:'resolved',note:'Review completed safely'},db});assert.equal(response.status,404);assert.equal(writes.length,1);});
test('safety report pagination is bounded and latest operator action returned',async()=>{const db={auditLog:{findMany:async q=>{assert.equal(q.take,51);return[{id:reportId,metadata:{description:'Example unsafe answer'},createdAt:new Date(0)}];},findFirst:async q=>{assert.equal(q.where.resourceId,reportId);return{metadata:{status:'reviewing'}};}}};const response=await triage({db});assert.equal(response.status,200);assert.equal(response.data.reports[0].triage.metadata.status,'reviewing');assert.equal(response.data.next_cursor,null);});
