import {createHmac} from 'node:crypto';
import {verifyHarnessRunnerServiceToken} from '../../src/harness-chat/runner-service-token.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {nativeSessionHash,nativeRunnerPrincipalAllowed} from '../../src/mobile/native-principal.js';
import {AI_DISCLOSURE_VERSION} from '../../src/mobile/privacy-routes.js';
import {mintHarnessAdmissionTicket,verifyHarnessAdmissionTicket} from '../../src/harness-chat/admission-ticket.js';
const user='11111111-1111-4111-8111-111111111111';const org='22222222-2222-4222-8222-222222222222';const token='native-session-secret';const hash=nativeSessionHash(token);
const records=new Map([[`cp:mobile-native-index:${hash}`,token],[`cp:session:${token}`,JSON.stringify({userId:user,orgId:org,nativeMobile:true})]]);
function input(){return{claims:{sub:user,org_id:org,native_session_hash:hash},prisma:{auditLog:{findFirst:async()=>({metadata:{version:AI_DISCLOSURE_VERSION,granted:true}})}},getRedis:async()=>({get:async k=>records.get(k) || null})};}
test('signed native binding remains opaque and optional for web tickets',()=>{const base={secret:'s'.repeat(32),userId:user,orgId:org,variation:'harness'};const native=mintHarnessAdmissionTicket({...base,nativeSessionHash:hash});assert.equal(verifyHarnessAdmissionTicket(native.ticket,{secret:base.secret}).native_session_hash,hash);assert.equal(native.ticket.includes(token),false);assert.equal(mintHarnessAdmissionTicket(base).claims.native_session_hash,undefined);assert.throws(()=>mintHarnessAdmissionTicket({...base,nativeSessionHash:'invalid'}));});
test('current consent withdrawal denies previously valid native principal with no positive cache',async()=>{const ctx=input();assert.equal(await nativeRunnerPrincipalAllowed(ctx),true);ctx.prisma.auditLog.findFirst=async()=>({metadata:{version:AI_DISCLOSURE_VERSION,granted:false}});assert.equal(await nativeRunnerPrincipalAllowed(ctx),false);});
test('revoked session and changed org deny old Runner grant while web remains unchanged',async()=>{const ctx=input();const original=records.get(`cp:session:${token}`);records.delete(`cp:session:${token}`);assert.equal(await nativeRunnerPrincipalAllowed(ctx),false);records.set(`cp:session:${token}`,JSON.stringify({userId:user,orgId:'other',nativeMobile:true}));assert.equal(await nativeRunnerPrincipalAllowed(ctx),false);records.set(`cp:session:${token}`,original);assert.equal(await nativeRunnerPrincipalAllowed({claims:{sub:user,org_id:org}}),true);});
test('spoofed user, invalid marker and backend outage fail closed',async()=>{const ctx=input();assert.equal(await nativeRunnerPrincipalAllowed({...ctx,claims:{...ctx.claims,sub:'other'}}),false);assert.equal(await nativeRunnerPrincipalAllowed({...ctx,claims:{...ctx.claims,native_session_hash:'bad'}}),false);assert.equal(await nativeRunnerPrincipalAllowed({...ctx,getRedis:async()=>null}),false);assert.equal(await nativeRunnerPrincipalAllowed({...ctx,getRedis:async()=>{throw Error('offline');}}),false);});

test('runner native session marker is cryptographically bound and malformed claims denied',async()=>{const secret='x'.repeat(32);const now=Math.floor(Date.now()/1000);const claims={iss:'hivemind-harness-runner',aud:'hivemind-control-plane-harness-proxy',sub:user,org_id:org,profile:'hivemind-chat',jti:'33333333-3333-4333-8333-333333333333',iat:now,exp:now+30,native_session_hash:hash};const sign=c=>{const input=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify(c)).toString('base64url');return input+'.'+createHmac('sha256',secret).update(input).digest('base64url');};const verified=verifyHarnessRunnerServiceToken(sign(claims),{secret});assert.equal(await nativeRunnerPrincipalAllowed({...input(),claims:verified}),true);assert.throws(()=>verifyHarnessRunnerServiceToken(sign({...claims,native_session_hash:'bad'}),{secret}));});
