import test from 'node:test';import assert from 'node:assert/strict';
import {handleMobilePrivacyRoutes,AI_DISCLOSURE_VERSION} from '../../src/mobile/privacy-routes.js';
const userId='user-a';
function fixture({method='POST',pathname='/v1/mobile/privacy/ai-consent',body={},signedIn=true,fail=false,latest=null}={}){const writes=[];let response;return{writes,get response(){return response},args:{req:{method},res:{},pathname,prisma:{auditLog:{findFirst:async ({where})=>{assert.equal(where.userId,userId);return latest;},create:async({data})=>{if(fail)throw Error('db');writes.push(data);return{id:'receipt-1',createdAt:new Date(0)};}}},requireSession:async()=>signedIn?{session:{userId}}:null,parseBody:async()=>body,jsonResponse:(_res,data,status)=>{response={data,status};}}};}
test('unrelated route untouched',async()=>{const f=fixture({pathname:'/v1/bootstrap'});assert.equal(await handleMobilePrivacyRoutes(f.args),false);assert.equal(f.writes.length,0);});
test('requires session; no client actor accepted',async()=>{const f=fixture({signedIn:false,body:{version:AI_DISCLOSURE_VERSION,granted:true}});await handleMobilePrivacyRoutes(f.args);assert.equal(f.writes.length,0);});
test('persists explicit current disclosure by authenticated person',async()=>{const f=fixture({body:{version:AI_DISCLOSURE_VERSION,granted:true,userId:'other-user',organizationId:'other-org'}});await handleMobilePrivacyRoutes(f.args);assert.equal(f.response.status,201);assert.equal(f.writes[0].userId,userId);assert.equal(f.writes[0].organizationId,undefined);assert.equal(f.writes[0].metadata.granted,true);assert.equal(f.response.data.receipt_id,'receipt-1');});
test('refuses stale or implicit consent',async()=>{for(const body of [{version:'old',granted:true},{version:AI_DISCLOSURE_VERSION,granted:'true'}]){const f=fixture({body});await handleMobilePrivacyRoutes(f.args);assert.equal(f.response.status,400);assert.equal(f.writes.length,0);}});
test('withdrawal receipt and lookup scoped to user',async()=>{const f=fixture({body:{version:AI_DISCLOSURE_VERSION,granted:false}});await handleMobilePrivacyRoutes(f.args);assert.equal(f.writes[0].action,'withdraw');const g=fixture({method:'GET',latest:{id:'last',metadata:f.writes[0].metadata}});await handleMobilePrivacyRoutes(g.args);assert.equal(g.response.data.granted,false);});
test('stale grant never permits new disclosure',async()=>{const f=fixture({method:'GET',latest:{id:'old',metadata:{granted:true,version:'old'}}});await handleMobilePrivacyRoutes(f.args);assert.equal(f.response.data.granted,false);});
test('report persists only provided description and opaque reference, no chat fetch',async()=>{const f=fixture({pathname:'/v1/mobile/safety-reports',body:{category:'hate',description:'The response contained harassment.',userId:'other',full_conversation:'never copy'}});await handleMobilePrivacyRoutes(f.args);assert.equal(f.response.status,201);assert.equal(f.writes[0].eventType,'mobile.ai_safety_report');assert.equal(f.writes[0].metadata.full_conversation,undefined);assert.equal(f.writes[0].userId,userId);});
test('invalid reports and methods rejected',async()=>{for(const body of [{category:'invalid',description:'This is a description'},{category:'harmful',description:'short'},{category:'harmful',description:'x'.repeat(4001)}]){const f=fixture({pathname:'/v1/mobile/safety-reports',body});await handleMobilePrivacyRoutes(f.args);assert.equal(f.response.status,400);assert.equal(f.writes.length,0);}const f=fixture({method:'DELETE'});await handleMobilePrivacyRoutes(f.args);assert.equal(f.response.status,405);});
test('storage failure never claims saved',async()=>{const f=fixture({body:{version:AI_DISCLOSURE_VERSION,granted:true},fail:true});await handleMobilePrivacyRoutes(f.args);assert.equal(f.response.status,503);assert.equal(f.response.data.receipt_id,undefined);});
