/**
 * Post-quantum signing service (NIST FIPS 204 ML-DSA + FIPS 205 SLH-DSA).
 *
 * - Memory write integrity → ML-DSA-65 (ml_dsa65): fast, per-write.
 * - Audit-log tamper-evidence → SLH-DSA-SHA2-128s: conservative hash-based,
 *   chained (prev_hash → entry_hash) so the whole trail is append-only verifiable.
 *
 * Secret keys live ONLY in env (PQC_*_SK), separate from the database, so an
 * attacker with DB access cannot forge valid signatures. Public keys (PQC_*_PK)
 * are exposed for independent verification. If keys/lib are absent every call
 * returns null/false and the caller proceeds unsigned — signing never breaks the
 * main flow.
 *
 * Keys are generated by scripts/pqc-keygen.mjs and set in the server env.
 */
import crypto from 'node:crypto';

let _ml = null, _slh = null, _loaded = false, _loadFailed = false;
async function load() {
  if (_loaded || _loadFailed) return !_loadFailed;
  try {
    const [{ ml_dsa65 }, slh] = await Promise.all([
      import('@noble/post-quantum/ml-dsa.js'),
      import('@noble/post-quantum/slh-dsa.js'),
    ]);
    _ml = ml_dsa65;
    _slh = slh.slh_dsa_sha2_128s;
    _loaded = true;
    return true;
  } catch (e) {
    _loadFailed = true;
    console.warn('[pqc] @noble/post-quantum not available — signing disabled:', e.message);
    return false;
  }
}

const b64 = (u8) => Buffer.from(u8).toString('base64');
const unb64 = (s) => new Uint8Array(Buffer.from(String(s), 'base64'));
const env = (k) => (process.env[k] || '').trim();

export function sha256Hex(s) { return crypto.createHash('sha256').update(String(s)).digest('hex'); }

// Deterministic JSON so the signed bytes are reproducible at verify time.
export function canonical(obj) {
  if (obj === null || typeof obj !== 'object') return JSON.stringify(obj ?? null);
  if (Array.isArray(obj)) return `[${obj.map(canonical).join(',')}]`;
  return `{${Object.keys(obj).sort().map((k) => `${JSON.stringify(k)}:${canonical(obj[k])}`).join(',')}}`;
}

export function pqcStatus() {
  return {
    memory_alg: 'ML-DSA-65 (FIPS 204)',
    audit_alg: 'SLH-DSA-SHA2-128s (FIPS 205)',
    memory_key_loaded: !!env('PQC_MEMORY_SK') && !!env('PQC_MEMORY_PK'),
    audit_key_loaded: !!env('PQC_AUDIT_SK') && !!env('PQC_AUDIT_PK'),
  };
}
export function publicKeys() {
  return {
    ml_dsa65: env('PQC_MEMORY_PK') || null,
    slh_dsa_sha2_128s: env('PQC_AUDIT_PK') || null,
  };
}

// ── Memory integrity (ML-DSA-65) ──
export async function signMemory(payloadStr) {
  const sk = env('PQC_MEMORY_SK');
  if (!sk || !(await load())) return null;
  // @noble/post-quantum 0.6.x: sign(message, secretKey), verify(signature, message, publicKey)
  try { return b64(_ml.sign(Buffer.from(payloadStr, 'utf8'), unb64(sk))); }
  catch (e) { console.warn('[pqc] memory sign failed:', e.message); return null; }
}
export async function verifyMemory(payloadStr, sigB64) {
  const pk = env('PQC_MEMORY_PK');
  if (!pk || !sigB64 || !(await load())) return false;
  try { return _ml.verify(unb64(sigB64), Buffer.from(payloadStr, 'utf8'), unb64(pk)); }
  catch { return false; }
}

// ── Audit tamper-evidence (SLH-DSA) ──
export async function signAudit(payloadStr) {
  const sk = env('PQC_AUDIT_SK');
  if (!sk || !(await load())) return null;
  try { return b64(_slh.sign(Buffer.from(payloadStr, 'utf8'), unb64(sk))); }
  catch (e) { console.warn('[pqc] audit sign failed:', e.message); return null; }
}
export async function verifyAudit(payloadStr, sigB64) {
  const pk = env('PQC_AUDIT_PK');
  if (!pk || !sigB64 || !(await load())) return false;
  try { return _slh.verify(unb64(sigB64), Buffer.from(payloadStr, 'utf8'), unb64(pk)); }
  catch { return false; }
}
