/** Actual native services in the same disposable PostgreSQL fixture; no external model calls. */
export async function nativePluginProof({admin,db,principal,checks,manageNativeEmployee,nativeLifecycleHostProof,assert}) {
 const repo='/opt/deepseek-harness';
 const load=async(path)=>import(`${repo}/${path}`);
 const {Context}=await load('vendor/cordis/lib/index.js');
 const {SessionId}=await load('packages/core/session/lib/index.js');
 const {default:Scope}=await load('packages/hivemind/execution-scope/lib/index.js');
 const {mountAgentLoopTestDependencies}=await load('packages/test-support/agent-loop-testkit/lib/index.js');
 const {default:Loop}=await load('packages/core/agent-loop/lib/index.js');
 const {PostgresSessionPersistence}=await load('packages/session/session-persistence-postgres/lib/index.js');
 const {default:Subagent}=await load('packages/subagent/subagent/lib/index.js');
 const {default:Team}=await load('packages/experimental/agent-team/lib/index.js');
 const {default:ScheduleBackend}=await load('packages/hivemind/schedule-postgres/lib/index.js');
 const {default:Schedule}=await load('packages/schedule/schedule/lib/index.js');
 const {default:HqOwnership}=await load('packages/hivemind/hq-runtime/lib/ownership.js');
 const {default:HqControl}=await load('packages/hivemind/hq-runtime/lib/control.js');
 const Hq=await load('packages/hivemind/hq-runtime/lib/index.js');
 const {RoomMessaging}=await load('packages/api/session-controller/src/room-messaging.ts');
 const {MockAdapter,textResponse,toolCallResponse}=await load('packages/core/agent-loop/tests/mock-adapter.ts');
 const {default:Attachments}=await load('packages/attachment/attachment-local/lib/index.js');
 const {GenerationRegistry,registerGenerationTools}=await load('packages/hivemind/artifact-renderer/src/generation.ts');
 const {markdownReportProvider}=await load('packages/hivemind/artifact-renderer/src/office-providers.ts');
 const fs=await import('node:fs');
 await admin.query(fs.readFileSync('/source/schedule.sql','utf8'));
 await admin.query('GRANT SELECT,INSERT,UPDATE,DELETE ON harness_scheduled_tasks,harness_scheduled_due TO fixture_runner');
 await admin.query('UPDATE fixture_memberships SET is_active=true');
 await admin.query('ALTER TABLE users ADD COLUMN deleted_at timestamptz; CREATE TABLE user_organizations AS SELECT org_id,user_id,is_active,NULL::timestamptz AS deactivated_at FROM fixture_memberships; GRANT SELECT ON users,user_organizations TO fixture_runner');
 const employee=(await manageNativeEmployee(db,{orgId:principal.orgId,userId:principal.userId},{operation:'create',creation_key:'native-plugin-proof',name:'Dummy Native Specialist',persona:'Isolated verification only.',lifecycle:'durable'},{now:0})).employee;
 const ctx=new Context();const scope=new Scope(ctx);
 process.env.FIXTURE_LOCAL_DB='postgresql://fixture_runner@127.0.0.1:5432/security_test';
 try { await scope.run(principal,async()=>{
  await mountAgentLoopTestDependencies(ctx);
  await ctx.plugin(PostgresSessionPersistence,{connectionStringEnv:'FIXTURE_LOCAL_DB',schema:'hivemind',leaseTtlMs:30000,maxConnections:2});
  await ctx.plugin(Loop,{agents:[]});await ctx.plugin(Subagent);
  ctx.provide('agentPresets',{composedPreset:()=>undefined,composeFrom:()=>undefined,serviceFor:(_agent,name)=>ctx.get(name)});
  await ctx.plugin(Team);
  const mockRegistration=ctx.llm.registerAdapter(['mock'],new MockAdapter([toolCallResponse('fixture-generate','hivemind_generate',{format:'markdown_report',title:'Isolated native brief',content:'# Isolated native brief\n\nThis is isolated fixture verification.'}),textResponse('Fixture scheduled work completed with saved brief.')]));
  const chief=await ctx.agentLoop.create(SessionId('session-native-plugin-chief'),{provider:'mock',model:'mock'});
  chief.session.append('agent-preset/selected',{agentPreset:'hivemind-hq'});
  chief.session.append('hivemind/session-owner',{id:null,slug:'runtime',name:'Runtime',role:'Chief'});
  chief.session.append('hivemind/hq-mode',{enabled:true,revision:1,changedAt:Date.now()});
  await ctx.sessions.flush(chief.session);
  const open=async key=>{
   const old=ctx.agents.get(SessionId(key));if(old) return old;
   const room=await ctx.agentLoop.create(SessionId(key),{provider:'mock',model:'mock'});
   room.session.append('agent-preset/selected',{agentPreset:'hivemind-hyperagents'});
   room.session.append('hivemind/session-owner',{id:employee.id,slug:employee.slug,name:employee.name,role:employee.roleArchetype});
   await ctx.sessions.flush(room.session);return room;
  };
  const messaging=new RoomMessaging(ctx,open);
  ctx.provide('sessionController',{resolvePersistentEmployeeRoom:(key,profile,signal)=>messaging.resolveRoom(key,profile,signal),deliverAgentMessage:messaging.send.bind(messaging),resolveAgent:async id=>({agent:await open(id)})});
  ctx.provide('storageDomain',{});
  await ctx.plugin(ScheduleBackend,{connectionStringEnv:'FIXTURE_LOCAL_DB',schema:'hivemind',pollIntervalMs:100,retryIntervalMs:1000,batchSize:8,maxConnections:2,statementTimeoutMs:2000,maxTasksPerUser:32});
  await ctx.plugin(Schedule,{storage:'external',deliveryPolicyRequired:true});
  await ctx.plugin(HqOwnership);ctx.hivemindHqOwnership.register({claim:async()=>{}});
  ctx.provide('hivemindEmployeeDirectory',{profiles:async()=>({profiles:[{id:employee.id,slug:employee.slug,name:employee.name,persona:employee.persona,role_archetype:employee.roleArchetype,status:employee.status,policy_rules:employee.policyRules}]})});
  await ctx.plugin(HqControl);await ctx.plugin(Hq);
  await ctx.plugin(Attachments,{dshHome:'/scratch/native-attachments'});
  const registry=new GenerationRegistry();registry.register(markdownReportProvider);registerGenerationTools(ctx,registry,'artifacts',4096,true);
  const task=await ctx.agentTeams.createTask(chief,{subject:'Fixture actual native task',description:'Save and review an isolated brief.',writeScopes:[]});
  const tool=ctx.tools.get('hivemind_hq_contract',chief);
  const signal=new AbortController().signal;
  const execute=async args=>tool.execute(args,{agent:chief,signal});
  const start=new Date(Date.now()+2000).toISOString(),end=new Date(Date.now()+10000).toISOString();
  await execute({action:'attach',task_id:task.id,due_at:end,acceptance_criteria:['A saved brief stating isolated fixture verification.']});
  await execute({action:'schedule',task_id:task.id,employee_id:employee.id,starts_at:start,ends_at:end});
  const target=ctx.agentTeams.listMembers(chief).find(member=>member.name===employee.slug);
  assert.ok(target);const worker=ctx.agents.get(target.id);
  worker.session.append('agent-preset/selected',{agentPreset:'hivemind-hyperagents'});
  worker.session.append('hivemind/session-owner',{id:employee.id,slug:employee.slug,name:employee.name,role:employee.roleArchetype});
  await ctx.sessions.flush(worker.session);await ctx.sessions.flush(chief.session);
  const catalog=await ctx.schedule.catalog();assert.ok(catalog.some(row=>row.sessionId===worker.id&&row.scheduledAt===start));
  checks.push('actual native Teams persistent assignment and PostgreSQL Schedule exact start receipt');
  for(let n=0;n<100&&!worker.session.ownEvents().some(event=>event.type==='turn/end');n++) await new Promise(resolve=>setTimeout(resolve,50));
  assert.ok(worker.session.ownEvents().some(event=>event.type==='turn/end'));checks.push('actual native PostgreSQL Schedule dispatch reaches persistent employee AgentLoop');
  const artifact=worker.session.ownEvents().findLast(event=>event.type==='hivemind/generation-created');assert.ok(artifact);
  await ctx.sessions.flush(worker.session);
  await execute({action:'artifacts',task_id:task.id,producer:employee.slug,artifact_ids:[artifact.data.artifactId]});
  const inspected=await execute({action:'inspect',task_id:task.id});assert.ok(JSON.stringify(inspected.documents).includes('isolated fixture verification'),JSON.stringify(inspected).slice(0,1500));
  await assert.rejects(ctx.agentTeams.updateTask(chief,{taskId:task.id,expectedRevision:inspected.task_revision,action:'complete'}),/accepted review/);
  await execute({action:'decide',task_id:task.id,task_revision:inspected.task_revision,evidence_hash:inspected.evidence_hash,decision:'accepted',rationale:'The exact saved fixture brief meets its isolated criterion.'});
  await ctx.agentTeams.updateTask(chief,{taskId:task.id,expectedRevision:inspected.task_revision,action:'complete'});
  await ctx.sessions.flush(chief.session);
  checks.push('actual artifact generation linking inspection and Runtime acceptance gate precede native Team completion');
  let closeout=await manageNativeEmployee(db,{orgId:principal.orgId,userId:principal.userId},{operation:'inspect_closeout',employee_id:employee.id});
  assert.ok(closeout.closeout.blockers.includes('verified_private_closeout_required'));
  await admin.query("INSERT INTO fixture_memories VALUES('native-plugin-handoff',$1,$2,'recorded','handoff',now())",[principal.orgId,employee.slug]);
  const archived=await manageNativeEmployee(db,{orgId:principal.orgId,userId:principal.userId,runtimeSessionId:chief.id},{operation:'archive',employee_id:employee.id,expected_revision:1});
  assert.equal(archived.employee.policyRules.native_lifecycle.phase,'archived');
  const retained=await ctx.sessionPersistence.open(worker.id,'read');await retained.read();await retained.close();
  checks.push('Core archives actual native accepted task plus recorded private handoff while preserving employee history');
  mockRegistration();
  const {nativeSetupProof}=await import('/source/native-employee-setup.pg.mjs');
  await nativeSetupProof({ctx,scope,principal,db,chief,checks,manageNativeEmployee,nativeLifecycleHostProof,assert,documents:inspected.documents});
 }); } finally {await ctx.fiber.dispose();delete process.env.FIXTURE_LOCAL_DB;}
}
