/**
 * PageIndex Service — Hierarchical Memory Index
 *
 * OPTIONAL optimization layer: Stores memory IDs organized by topic/project.
 * Never blocks ingestion or search — graceful fallback to PostgreSQL + VectorDB.
 *
 * Key features:
 * - Max 4 levels deep (prevents over-nesting)
 * - Memory ID can be in multiple nodes (cross-referencing)
 * - Auto-generated nodes (CSI evolves structure over time)
 * - Silent failure if PageIndex unavailable
 */

export class PageIndexService {
  constructor({ prisma, logger = console }) {
    this.prisma = prisma;
    this.logger = logger;
    this.MAX_DEPTH = 4;
    this.ROOT_PATH = '/hivemind';
  }

  /**
   * Check if PageIndex table exists (first-run safety).
   */
  async isAvailable() {
    try {
      await this.prisma.$queryRaw`SELECT 1 FROM "PageIndexNode" LIMIT 1`;
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Get or create root node for user.
   */
  async ensureRootNode(userId, orgId = null) {
    try {
      const existing = await this.prisma.pageIndexNode.findFirst({
        where: { userId, path: this.ROOT_PATH, parentId: null },
      });

      if (existing) return existing;

      return await this.prisma.pageIndexNode.create({
        data: {
          userId,
          orgId,
          label: 'root',
          path: this.ROOT_PATH,
          nodeType: 'root',
          depth: 1,
          autoGenerated: true,
        },
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] ensureRootNode failed:', err.message);
      return null;
    }
  }

  /**
   * Create a new node in the hierarchy.
   * @param {object} params
   * @param {string} params.userId
   * @param {string|null} params.orgId
   * @param {string|null} params.parentId - Parent node ID (null for root-level)
   * @param {string} params.label - Human-readable name
   * @param {string} [params.nodeType='topic'] - root, category, topic, subtopic, person
   * @returns {Promise<object|null>} Created node or null if failed/invalid
   */
  async createNode({ userId, orgId, parentId, label, nodeType = 'topic' }) {
    try {
      // Determine depth and path
      let depth = 2;
      let path = `${this.ROOT_PATH}/${this._slugify(label)}`;

      if (parentId) {
        const parent = await this.prisma.pageIndexNode.findUnique({
          where: { id: parentId },
          select: { depth: true, path: true, userId: true },
        });

        if (!parent || parent.userId !== userId) {
          this.logger.warn('[PageIndexService] Invalid parent node');
          return null;
        }

        if (parent.depth >= this.MAX_DEPTH) {
          this.logger.warn('[PageIndexService] Max depth reached, cannot create child');
          return null;
        }

        depth = parent.depth + 1;
        path = `${parent.path}/${this._slugify(label)}`;
      }

      // Check for existing node with same path
      const existing = await this.prisma.pageIndexNode.findFirst({
        where: { userId, path },
      });

      if (existing) return existing;

      return await this.prisma.pageIndexNode.create({
        data: {
          userId,
          orgId,
          parentId,
          label,
          path,
          nodeType,
          depth,
          autoGenerated: true,
        },
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] createNode failed:', err.message);
      return null;
    }
  }

  /**
   * Find node by full path.
   */
  async findNodeByPath(userId, path) {
    try {
      return await this.prisma.pageIndexNode.findFirst({
        where: { userId, path },
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] findNodeByPath failed:', err.message);
      return null;
    }
  }

  /**
   * Get full tree for user.
   */
  async getTree(userId, options = {}) {
    try {
      const { depth = 4, rootPath = this.ROOT_PATH } = options;

      const nodes = await this.prisma.pageIndexNode.findMany({
        where: {
          userId,
          path: { startsWith: rootPath },
          depth: { lte: depth },
          deletedAt: null,
        },
        orderBy: [{ depth: 'asc' }, { path: 'asc' }],
      });

      return this._buildTree(nodes);
    } catch (err) {
      this.logger.warn('[PageIndexService] getTree failed:', err.message);
      return null;
    }
  }

  /**
   * Safe tree fetch — returns empty array if PageIndex unavailable.
   */
  async getTreeSafe(userId, options = {}) {
    const available = await this.isAvailable();
    if (!available) return [];

    return this.getTree(userId, options) || [];
  }

  /**
   * Assign memory ID to node (adds to memoryIds array).
   */
  async assignMemoryToNode(nodeId, memoryId) {
    try {
      const node = await this.prisma.pageIndexNode.findUnique({
        where: { id: nodeId },
        select: { memoryIds: true, memoryCount: true },
      });

      if (!node) return false;

      // Avoid duplicates
      if (node.memoryIds.includes(memoryId)) {
        return true; // Already assigned
      }

      await this.prisma.pageIndexNode.update({
        where: { id: nodeId },
        data: {
          memoryIds: [...node.memoryIds, memoryId],
          memoryCount: node.memoryIds.length + 1,
        },
      });

      return true;
    } catch (err) {
      this.logger.warn('[PageIndexService] assignMemoryToNode failed:', err.message);
      return false;
    }
  }

  /**
   * Remove memory ID from node.
   */
  async removeMemoryFromNode(nodeId, memoryId) {
    try {
      const node = await this.prisma.pageIndexNode.findUnique({
        where: { id: nodeId },
        select: { memoryIds: true },
      });

      if (!node) return false;

      const newMemoryIds = node.memoryIds.filter(id => id !== memoryId);

      await this.prisma.pageIndexNode.update({
        where: { id: nodeId },
        data: {
          memoryIds: newMemoryIds,
          memoryCount: newMemoryIds.length,
        },
      });

      return true;
    } catch (err) {
      this.logger.warn('[PageIndexService] removeMemoryFromNode failed:', err.message);
      return false;
    }
  }

  /**
   * Assign memory to multiple nodes (cross-referencing).
   */
  async assignMemoryToNodes(nodeIds, memoryId) {
    const results = await Promise.all(
      nodeIds.map(id => this.assignMemoryToNode(id, memoryId))
    );
    return results.filter(r => r).length;
  }

  /**
   * Find all nodes containing a specific memory.
   */
  async findNodesForMemory(memoryId) {
    try {
      return await this.prisma.pageIndexNode.findMany({
        where: {
          memoryIds: { has: memoryId },
          deletedAt: null,
        },
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] findNodesForMemory failed:', err.message);
      return [];
    }
  }

  /**
   * Get children of a node.
   */
  async findChildren(parentId, options = {}) {
    try {
      const { depth = 1 } = options;

      const parent = await this.prisma.pageIndexNode.findUnique({
        where: { id: parentId },
        select: { depth: true, userId: true },
      });

      if (!parent) return [];

      return await this.prisma.pageIndexNode.findMany({
        where: {
          userId: parent.userId,
          parentId,
          depth: { lte: parent.depth + depth },
          deletedAt: null,
        },
        orderBy: [{ depth: 'asc' }, { label: 'asc' }],
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] findChildren failed:', err.message);
      return [];
    }
  }

  /**
   * Delete a node and optionally reassign its memories.
   */
  async deleteNode(nodeId, options = {}) {
    try {
      const { reassignMemories = false, targetNodeId = null } = options;

      const node = await this.prisma.pageIndexNode.findUnique({
        where: { id: nodeId },
        select: { memoryIds: true },
      });

      if (!node) return false;

      // Reassign memories before deletion
      if (reassignMemories && targetNodeId && node.memoryIds.length > 0) {
        await this.assignMemoryToNodes([targetNodeId], node.memoryIds);
      }

      // Soft delete
      await this.prisma.pageIndexNode.update({
        where: { id: nodeId },
        data: { deletedAt: new Date() },
      });

      return true;
    } catch (err) {
      this.logger.warn('[PageIndexService] deleteNode failed:', err.message);
      return false;
    }
  }

  /**
   * Prune sparse nodes (auto-evolution).
   * Deletes nodes with < minMemories after daysOld days.
   */
  async pruneSparseNodes(userId, options = {}) {
    try {
      const { minMemories = 5, daysOld = 30 } = options;

      const cutoffDate = new Date();
      cutoffDate.setDate(cutoffDate.getDate() - daysOld);

      const sparseNodes = await this.prisma.pageIndexNode.findMany({
        where: {
          userId,
          memoryCount: { lt: minMemories },
          createdAt: { lt: cutoffDate },
          autoGenerated: true,
          customBranch: false,
          deletedAt: null,
        },
        select: { id: true, parentId: true, memoryIds: true },
      });

      let pruned = 0;
      for (const node of sparseNodes) {
        // Reassign memories to parent if possible
        if (node.parentId && node.memoryIds.length > 0) {
          await this.assignMemoryToNodes([node.parentId], node.memoryIds);
        }

        await this.deleteNode(node.id);
        pruned++;
      }

      if (pruned > 0) {
        this.logger.log(`[PageIndexService] Pruned ${pruned} sparse nodes`);
      }

      return pruned;
    } catch (err) {
      this.logger.warn('[PageIndexService] pruneSparseNodes failed:', err.message);
      return 0;
    }
  }

  /**
   * Build nested tree from flat node array.
   * @private
   */
  _buildTree(nodes) {
    const root = { children: [] };
    const nodeMap = new Map();

    // Create node map
    for (const node of nodes) {
      nodeMap.set(node.id, { ...node, children: [] });
    }

    // Build tree
    for (const node of nodeMap.values()) {
      if (!node.parentId || !nodeMap.has(node.parentId)) {
        root.children.push(node);
      } else {
        const parent = nodeMap.get(node.parentId);
        parent.children.push(node);
      }
    }

    return root.children;
  }

  /**
   * Slugify label for path generation.
   * @private
   */
  _slugify(text) {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
  }

  /**
   * Get memory count for a node (cached or computed).
   * @private
   */
  _computeMemoryCount(node) {
    return node.memoryIds?.length || 0;
  }
}
