/**
 * PageIndex Service — Hierarchical Memory Index
 *
 * OPTIONAL optimization layer: Stores memory IDs organized by topic/project.
 * Never blocks ingestion or search — graceful fallback to PostgreSQL + VectorDB.
 *
 * Key features:
 * - Max 4 levels deep (prevents over-nesting)
 * - Memory ID can be in multiple nodes (cross-referencing)
 * - Auto-generated nodes (CSI evolves structure over time)
 * - Silent failure if PageIndex unavailable
 */

export class PageIndexService {
  constructor({ prisma, logger = console }) {
    this.prisma = prisma;
    this.logger = logger;
    this.MAX_DEPTH = 4;
    this.ROOT_PATH = '/hivemind';
  }

  /**
   * Check if PageIndex table exists (first-run safety).
   */
  async isAvailable() {
    try {
      await this.prisma.$queryRaw`SELECT 1 FROM "PageIndexNode" LIMIT 1`;
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Get or create root node for user.
   */
  async ensureRootNode(userId, orgId = null) {
    try {
      const existing = await this.prisma.pageIndexNode.findFirst({
        where: { userId, path: this.ROOT_PATH, parentId: null },
      });

      if (existing) return existing;

      return await this.prisma.pageIndexNode.create({
        data: {
          userId,
          orgId,
          label: 'root',
          path: this.ROOT_PATH,
          nodeType: 'root',
          depth: 1,
          autoGenerated: true,
        },
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] ensureRootNode failed:', err.message);
      return null;
    }
  }

  /**
   * Create a new node in the hierarchy.
   * @param {object} params
   * @param {string} params.userId
   * @param {string|null} params.orgId
   * @param {string|null} params.parentId - Parent node ID (null for root-level)
   * @param {string} params.label - Human-readable name
   * @param {string} [params.nodeType='topic'] - root, category, topic, subtopic, person
   * @returns {Promise<object|null>} Created node or null if failed/invalid
   */
  async createNode({ userId, orgId, parentId, label, nodeType = 'topic' }) {
    try {
      // Determine depth and path
      let depth = 2;
      let path = `${this.ROOT_PATH}/${this._slugify(label)}`;

      if (parentId) {
        const parent = await this.prisma.pageIndexNode.findUnique({
          where: { id: parentId },
          select: { depth: true, path: true, userId: true },
        });

        if (!parent || parent.userId !== userId) {
          this.logger.warn('[PageIndexService] Invalid parent node');
          return null;
        }

        if (parent.depth >= this.MAX_DEPTH) {
          this.logger.warn('[PageIndexService] Max depth reached, cannot create child');
          return null;
        }

        depth = parent.depth + 1;
        path = `${parent.path}/${this._slugify(label)}`;
      }

      // Check for existing node with same path
      const existing = await this.prisma.pageIndexNode.findFirst({
        where: { userId, path },
      });

      if (existing) return existing;

      return await this.prisma.pageIndexNode.create({
        data: {
          userId,
          orgId,
          parentId,
          label,
          path,
          nodeType,
          depth,
          autoGenerated: true,
        },
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] createNode failed:', err.message);
      return null;
    }
  }

  /**
   * Find node by full path.
   */
  async findNodeByPath(userId, path) {
    try {
      return await this.prisma.pageIndexNode.findFirst({
        where: { userId, path },
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] findNodeByPath failed:', err.message);
      return null;
    }
  }

  /**
   * Get full tree for user.
   */
  async getTree(userId, options = {}) {
    try {
      const { depth = 4, rootPath = this.ROOT_PATH } = options;

      const nodes = await this.prisma.pageIndexNode.findMany({
        where: {
          userId,
          path: { startsWith: rootPath },
          depth: { lte: depth },
          deletedAt: null,
        },
        orderBy: [{ depth: 'asc' }, { path: 'asc' }],
      });

      return this._buildTree(nodes);
    } catch (err) {
      this.logger.warn('[PageIndexService] getTree failed:', err.message);
      return null;
    }
  }

  /**
   * Safe tree fetch — returns empty array if PageIndex unavailable.
   */
  async getTreeSafe(userId, options = {}) {
    const available = await this.isAvailable();
    if (!available) return [];

    return this.getTree(userId, options) || [];
  }

  /**
   * Assign memory ID to node (adds to memoryIds array).
   */
  async assignMemoryToNode(nodeId, memoryId) {
    try {
      const node = await this.prisma.pageIndexNode.findUnique({
        where: { id: nodeId },
        select: { memoryIds: true, memoryCount: true },
      });

      if (!node) return false;

      // Avoid duplicates
      if (node.memoryIds.includes(memoryId)) {
        return true; // Already assigned
      }

      await this.prisma.pageIndexNode.update({
        where: { id: nodeId },
        data: {
          memoryIds: [...node.memoryIds, memoryId],
          memoryCount: node.memoryIds.length + 1,
        },
      });

      return true;
    } catch (err) {
      this.logger.warn('[PageIndexService] assignMemoryToNode failed:', err.message);
      return false;
    }
  }

  /**
   * Remove memory ID from node.
   */
  async removeMemoryFromNode(nodeId, memoryId) {
    try {
      const node = await this.prisma.pageIndexNode.findUnique({
        where: { id: nodeId },
        select: { memoryIds: true },
      });

      if (!node) return false;

      const newMemoryIds = node.memoryIds.filter(id => id !== memoryId);

      await this.prisma.pageIndexNode.update({
        where: { id: nodeId },
        data: {
          memoryIds: newMemoryIds,
          memoryCount: newMemoryIds.length,
        },
      });

      return true;
    } catch (err) {
      this.logger.warn('[PageIndexService] removeMemoryFromNode failed:', err.message);
      return false;
    }
  }

  /**
   * Assign memory to multiple nodes (cross-referencing).
   */
  async assignMemoryToNodes(nodeIds, memoryId) {
    const results = await Promise.all(
      nodeIds.map(id => this.assignMemoryToNode(id, memoryId))
    );
    return results.filter(r => r).length;
  }

  /**
   * Find all nodes containing a specific memory.
   */
  async findNodesForMemory(memoryId) {
    try {
      return await this.prisma.pageIndexNode.findMany({
        where: {
          memoryIds: { has: memoryId },
          deletedAt: null,
        },
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] findNodesForMemory failed:', err.message);
      return [];
    }
  }

  /**
   * Get children of a node.
   */
  async findChildren(parentId, options = {}) {
    try {
      const { depth = 1 } = options;

      const parent = await this.prisma.pageIndexNode.findUnique({
        where: { id: parentId },
        select: { depth: true, userId: true },
      });

      if (!parent) return [];

      return await this.prisma.pageIndexNode.findMany({
        where: {
          userId: parent.userId,
          parentId,
          depth: { lte: parent.depth + depth },
          deletedAt: null,
        },
        orderBy: [{ depth: 'asc' }, { label: 'asc' }],
      });
    } catch (err) {
      this.logger.warn('[PageIndexService] findChildren failed:', err.message);
      return [];
    }
  }

  /**
   * Delete a node and optionally reassign its memories.
   */
  async deleteNode(nodeId, options = {}) {
    try {
      const { reassignMemories = false, targetNodeId = null } = options;

      const node = await this.prisma.pageIndexNode.findUnique({
        where: { id: nodeId },
        select: { memoryIds: true },
      });

      if (!node) return false;

      // Reassign memories before deletion
      if (reassignMemories && targetNodeId && node.memoryIds.length > 0) {
        await this.assignMemoryToNodes([targetNodeId], node.memoryIds);
      }

      // Soft delete
      await this.prisma.pageIndexNode.update({
        where: { id: nodeId },
        data: { deletedAt: new Date() },
      });

      return true;
    } catch (err) {
      this.logger.warn('[PageIndexService] deleteNode failed:', err.message);
      return false;
    }
  }

  /**
   * Prune sparse nodes (auto-evolution).
   * Deletes nodes with < minMemories after daysOld days.
   */
  async pruneSparseNodes(userId, options = {}) {
    try {
      const { minMemories = 5, daysOld = 30 } = options;

      const cutoffDate = new Date();
      cutoffDate.setDate(cutoffDate.getDate() - daysOld);

      const sparseNodes = await this.prisma.pageIndexNode.findMany({
        where: {
          userId,
          memoryCount: { lt: minMemories },
          createdAt: { lt: cutoffDate },
          autoGenerated: true,
          customBranch: false,
          deletedAt: null,
        },
        select: { id: true, parentId: true, memoryIds: true },
      });

      let pruned = 0;
      for (const node of sparseNodes) {
        // Reassign memories to parent if possible
        if (node.parentId && node.memoryIds.length > 0) {
          await this.assignMemoryToNodes([node.parentId], node.memoryIds);
        }

        await this.deleteNode(node.id);
        pruned++;
      }

      if (pruned > 0) {
        this.logger.log(`[PageIndexService] Pruned ${pruned} sparse nodes`);
      }

      return pruned;
    } catch (err) {
      this.logger.warn('[PageIndexService] pruneSparseNodes failed:', err.message);
      return 0;
    }
  }

  /**
   * Get all memory IDs for a node (including children).
   * @param {string} nodeId - Node ID
   * @param {boolean} includeChildren - Include child node memories (default: true)
   * @returns {Promise<{ memoryIds: string[], count: number }>}
   */
  async getMemoriesForNode(nodeId, includeChildren = true) {
    try {
      const node = await this.prisma.pageIndexNode.findUnique({
        where: { id: nodeId },
        select: { memoryIds: true, children: includeChildren ? { select: { id: true, memoryIds: true } } : false },
      });

      if (!node) return { memoryIds: [], count: 0 };

      // Collect all memory IDs
      const allMemoryIds = new Set(node.memoryIds || []);

      if (includeChildren && node.children) {
        for (const child of node.children) {
          for (const id of child.memoryIds || []) {
            allMemoryIds.add(id);
          }
        }
      }

      return {
        memoryIds: Array.from(allMemoryIds),
        count: allMemoryIds.size,
      };
    } catch (err) {
      this.logger.warn('[PageIndexService] getMemoriesForNode failed:', err.message);
      return { memoryIds: [], count: 0 };
    }
  }

  /**
   * Generate summary for a node using LLM.
   * Summarizes all memories in the node.
   * @param {string} nodeId - Node ID
   * @returns {Promise<{ success: boolean }>}
   */
  async generateNodeSummary(nodeId) {
    try {
      const node = await this.prisma.pageIndexNode.findUnique({
        where: { id: nodeId },
        select: {
          id: true,
          userId: true,
          label: true,
          path: true,
          memoryIds: true,
          summary: true,
        },
      });

      if (!node || node.memoryIds.length === 0) {
        return { success: false, reason: 'no_memories' };
      }

      // Fetch memory content (limit to first 10 for context window)
      const memories = await this.prisma.memory.findMany({
        where: {
          id: { in: node.memoryIds.slice(0, 10) },
          deletedAt: null,
        },
        select: {
          id: true,
          title: true,
          content: true,
          tags: true,
          memoryType: true,
        },
        take: 10,
      });

      if (memories.length === 0) {
        return { success: false, reason: 'no_content' };
      }

      // Build context for LLM
      const memorySummaries = memories.map(m =>
        `- [${m.title || 'Untitled'}] (${m.memoryType}): ${truncate(m.content, 300)}`
      ).join('\n');

      const prompt = `Summarize this collection of ${node.memoryIds.length} memories (showing ${memories.length} samples) in the "${node.label}" topic.

${memorySummaries}

Write a 2-3 sentence summary describing what topics/themes this collection covers. Be specific and useful for retrieval.`;

      // Call LLM (using Groq if available, otherwise skip)
      const groqApiKey = process.env.GROQ_API_KEY;
      let summary = null;

      if (groqApiKey) {
        try {
          const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${groqApiKey}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              model: 'llama-3.1-8b-instant',
              messages: [
                { role: 'system', content: 'You are a summarization engine. Summarize memory collections concisely.' },
                { role: 'user', content: prompt },
              ],
              max_tokens: 200,
              temperature: 0.3,
            }),
          });

          if (response.ok) {
            const data = await response.json();
            summary = data.choices[0]?.message?.content || null;
          }
        } catch (err) {
          this.logger.warn('[PageIndexService] LLM summary failed, using fallback:', err.message);
        }
      }

      // Fallback: generate keyword-based summary
      if (!summary) {
        const allTags = memories.flatMap(m => m.tags || []);
        const tagCounts = {};
        for (const tag of allTags) {
          tagCounts[tag] = (tagCounts[tag] || 0) + 1;
        }
        const topTags = Object.entries(tagCounts)
          .sort((a, b) => b[1] - a[1])
          .slice(0, 5)
          .map(([tag]) => tag)
          .join(', ');

        summary = `Collection of ${node.memoryIds.length} memories covering: ${topTags || node.label}`;
      }

      // Update node
      await this.prisma.pageIndexNode.update({
        where: { id: nodeId },
        data: {
          summary,
          summaryUpdatedAt: new Date(),
        },
      });

      this.logger.log(`[PageIndexService] Generated summary for node ${nodeId.slice(0, 8)}`);
      return { success: true };
    } catch (err) {
      this.logger.warn('[PageIndexService] generateNodeSummary failed:', err.message);
      return { success: false, error: err.message };
    }
  }

  /**
   * Build nested tree from flat node array.
   * @private
   */
  _buildTree(nodes) {
    const root = { children: [] };
    const nodeMap = new Map();

    // Create node map
    for (const node of nodes) {
      nodeMap.set(node.id, { ...node, children: [] });
    }

    // Build tree
    for (const node of nodeMap.values()) {
      if (!node.parentId || !nodeMap.has(node.parentId)) {
        root.children.push(node);
      } else {
        const parent = nodeMap.get(node.parentId);
        parent.children.push(node);
      }
    }

    return root.children;
  }

  /**
   * Slugify label for path generation.
   * @private
   */
  _slugify(text) {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
  }

  /**
   * Get memory count for a node (cached or computed).
   * @private
   */
  _computeMemoryCount(node) {
    return node.memoryIds?.length || 0;
  }
}

function truncate(str, len = 300) {
  if (!str) return '';
  return str.length > len ? str.slice(0, len) + '...' : str;
}
