import test from 'node:test';
import assert from 'node:assert/strict';
import {completionToken,reconcileDelegatedConnections} from '../../src/harness-chat/delegated-connection-completion.js';
const blocker={id:'blocker-1',rootId:'chief',employeeId:'employee',employeeSessionId:'room',workflowSessionId:'upon',routerSessionId:'router',toolkits:['googlesheets']};
function fixture(){let calls=0;const ctx={orgId:'org',userId:'actor',prisma:{userOrganization:{findUnique:async()=>({isActive:true,role:'admin'})}}};
 const options={env:{HIVEMIND_EMPLOYEE_LIFECYCLE_URL:'http://runner/internal/hivemind/employee-lifecycle',HIVE_HARNESS_RUNNER_SERVICE_SECRET:'s'.repeat(32)},read:async()=>[blocker],verify:async()=>({verified:true}),fetchImpl:async(url,args)=>{calls++;assert.equal(url.pathname,'/internal/hivemind/delegated-connection');const body=JSON.parse(args.body);assert.equal(body.workflowSessionId,'upon');assert.equal(body.rootId,'chief');assert.equal(body.userId,'actor');assert(!('redirectUrl' in body));return{ok:true,text:async()=>JSON.stringify({status:'accepted',blockerId:'blocker-1',rootId:'chief'})}}};return{ctx,options,calls:()=>calls};}
test('late provider completion is checked with original workflow on every reconciliation',async()=>{const f=fixture();f.options.verify=async()=>({verified:false});const pending=await reconcileDelegatedConnections(f.ctx,f.options);assert.equal(pending.delivered,0);assert.equal(pending.status,'pending');assert.equal(pending.waiting,1);f.options.verify=async()=>({verified:true});assert.equal((await reconcileDelegatedConnections(f.ctx,f.options)).delivered,1);assert.equal(f.calls(),1)});
test('disconnected accounts and inactive actor never deliver',async()=>{const f=fixture();f.options.verify=async()=>({verified:false});await reconcileDelegatedConnections(f.ctx,f.options);assert.equal(f.calls(),0);f.ctx.prisma.userOrganization.findUnique=async()=>({isActive:false,role:'admin'});await reconcileDelegatedConnections(f.ctx,f.options);assert.equal(f.calls(),0)});
test('wrong owner verification rejects before any callback',async()=>{const f=fixture();f.options.verify=async()=>{throw Error('connection_actor_scope_mismatch')};assert.equal((await reconcileDelegatedConnections(f.ctx,f.options)).delivered,0);assert.equal(f.calls(),0)});
test('retries preserve identical payload for native mailbox deduplication',async()=>{const f=fixture();const payload=[];const original=f.options.fetchImpl;f.options.fetchImpl=async(url,args)=>{payload.push(args.body);return original(url,args)};await reconcileDelegatedConnections(f.ctx,f.options);await reconcileDelegatedConnections(f.ctx,f.options);assert.deepEqual(payload,[payload[0],payload[0]])});
test('signature binds complete body and separates audience from attention and lifecycle',()=>{const payload={orgId:'org',userId:'actor',blockerId:'b'};const token=completionToken(payload,'s'.repeat(32),100000);const claims=JSON.parse(Buffer.from(token.split('.')[1],'base64url'));assert.equal(claims.aud,'hivemind-delegated-connection');assert.equal(claims.sub,'actor');assert.equal(claims.exp-claims.iat,30);assert.equal(claims.body_sha256.length,64)});

test('coalesces concurrent owner checks but refreshes after settled connection change',async()=>{const f=fixture();let release;let reads=0;f.options.read=async()=>{reads++;await new Promise(r=>{release=r});return [blocker]};const a=reconcileDelegatedConnections(f.ctx,f.options),b=reconcileDelegatedConnections(f.ctx,f.options);await new Promise(r=>setImmediate(r));release();await Promise.all([a,b]);assert.equal(reads,1);assert.equal(f.calls(),1);f.options.read=async()=>{reads++;return [blocker]};await reconcileDelegatedConnections(f.ctx,f.options);assert.equal(reads,2)});
test('a failed workflow does not suppress another saved blocker',async()=>{const f=fixture();f.options.read=async()=>[{...blocker,employeeSessionId:'wrong'},blocker];f.options.verify=async({input})=>{if(input.session_id==='wrong')throw Error('denied');return{verified:true}};assert.equal((await reconcileDelegatedConnections(f.ctx,f.options)).delivered,1)});

test('no active blockers completes a refresh without a provider check',async()=>{const f=fixture();f.options.read=async()=>[];assert.equal((await reconcileDelegatedConnections(f.ctx,f.options)).status,'reconciled');assert.equal(f.calls(),0)});
