import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {handleHarnessChatBootstrapRoute} from '../../src/routes/harness-chat.js';
const secret='synthetic-refresh-fixture-secret-32-bytes';
const userId='54f5568b-4d6a-4ae1-9a33-48cb2909d59b',orgId='67503d34-97e9-49a8-8c52-8ee30cc7603e';
function token(){const now=Math.floor(Date.now()/1000),encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url');const input=`${encode({alg:'HS256',typ:'JWT'})}.${encode({iss:'hivemind-harness-runner',aud:'hivemind-control-plane-harness-proxy',sub:userId,org_id:orgId,profile:'hivemind-chat',iat:now,exp:now+30,jti:crypto.randomUUID()})}`;return `${input}.${crypto.createHmac('sha256',secret).update(input).digest('base64url')}`;}
async function invoke({body={},invalid=false,role='admin',method='POST'}={}){let reads=0;const res={};const prisma={userOrganization:{findUnique:async({where})=>{assert.equal(where.userId_orgId.userId,userId);assert.equal(where.userId_orgId.orgId,orgId);return {isActive:true,role}}},$transaction:async fn=>fn({$executeRawUnsafe:async()=>{},$queryRawUnsafe:async sql=>{reads++;if(sql.includes('information_schema'))return[{table_schema:'hivemind'}];return[]}})};await handleHarnessChatBootstrapRoute({req:{method,headers:{authorization:`Bearer ${invalid?'invalid':token()}`}},res,pathname:'/internal/v1/harness-chat/core/delegated-connection/refresh',prisma,env:{HIVE_HARNESS_RUNNER_SERVICE_SECRET:secret,HIVEMIND_EMPLOYEE_LIFECYCLE_URL:'http://runner/internal/hivemind/employee-lifecycle'},parseBody:async()=>body,jsonResponse:(r,b,status=200)=>Object.assign(r,{body:b,status}),fetchImpl:async()=>{throw Error('no callback expected')},redisConfig:{}});return{res,reads};}
test('signed empty refresh uses authenticated actor and no caller identifiers',async()=>{const {res,reads}=await invoke();assert.equal(res.status,200);assert.equal(res.body.status,'reconciled');assert(reads>0)});
test('rejects client-supplied authority before saved blocker reads',async()=>{for(const body of [{userId},{orgId},{success:true},[]]){const {res,reads}=await invoke({body});assert.equal(res.status,400);assert.equal(reads,0)}});
test('rejects unsigned caller, non-admin actor and wrong method',async()=>{assert.equal((await invoke({invalid:true})).res.status,401);assert.equal((await invoke({role:'member'})).res.status,403);assert.equal((await invoke({method:'GET'})).res.status,405)});
