import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeOrganizationPolicy,saveOrganizationPolicy,latestOrganizationPolicy,materializeOrganizationPolicy,handleOrganizationSettings,readOrganizationSettings} from '../../src/billing/organization-policy.js';
import {getEffectivePlan} from '../../src/billing/entitlements.js';
import {getPlan} from '../../src/billing/plans.js';import {PlanEnforcer} from '../../src/billing/plan-enforcer.js';import {CreditService} from '../../src/billing/credit-service.js';
const org='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',operator={operator:'Platform operator',sessionId:'33333333-3333-4333-8333-333333333333'};
function fixture(){const rows=new Map(),writes=[];const db={organization:{findUnique:async({where})=>[org,other].includes(where.id)?{id:where.id,name:'Company',plan:'free'}:null},userOrganization:{count:async()=>1},orgInvite:{count:async()=>1},$executeRawUnsafe:async(...args)=>writes.push(args),$queryRawUnsafe:async(sql,...args)=>{if(sql.startsWith('SELECT version'))return rows.has(args[0])?[rows.get(args[0])]:[];if(sql.startsWith('INSERT')){const row={version:args[1],limits:JSON.parse(args[2]),features:JSON.parse(args[3]),reason:args[4],created_at:new Date().toISOString()};rows.set(args[0],row);return[row];}throw Error('Unexpected query');},$transaction:async fn=>fn(db)};return{db,rows,writes};}
test('supported values are strict and balance/grants/unknown features cannot be fabricated',()=>{assert.deepEqual(normalizeOrganizationPolicy({revision:0,limits:{monthlyCredits:0,maxUsers:-1},features:{agentSwarm:false},reason:'Support change'}).limits,{monthlyCredits:0,maxUsers:-1});for(const bad of [{balance:500},{limits:{monthlyCredits:'500'}},{limits:{maxUsers:-2}},{features:{ssoSaml:true}},{features:{agentSwarm:'true'}},{orgId:other}])assert.throws(()=>normalizeOrganizationPolicy({revision:0,reason:'Support change',...bad}));});
test('policy is organization scoped, persistent and does not overwrite usage',async()=>{const{db,writes}=fixture();await saveOrganizationPolicy({prisma:db,orgId:org,input:{revision:0,limits:{monthlyCredits:3000,maxUsers:3},features:{agentSwarm:true},reason:'Pilot capacity'},operator});const row=await latestOrganizationPolicy(db,org);assert.equal(row.limits.monthlyCredits,3000);assert.equal(await latestOrganizationPolicy(db,other),null);const plan=materializeOrganizationPolicy(getPlan('free'),row);assert.equal(plan.limits.maxUsers,3);assert.equal(plan.features.agentSwarm,true);assert.equal(plan.inheritedLimits.maxUsers,1);assert.equal(writes.length,1);assert.match(writes[0][0],/advisory/);});
test('stale edits conflict and null removes only requested overrides',async()=>{const{db}=fixture();await saveOrganizationPolicy({prisma:db,orgId:org,input:{revision:0,limits:{monthlyCredits:3000,maxUsers:3},reason:'Pilot capacity'},operator});await assert.rejects(saveOrganizationPolicy({prisma:db,orgId:org,input:{revision:0,limits:{maxUsers:4},reason:'Stale edit'},operator}),e=>e.status===409);await saveOrganizationPolicy({prisma:db,orgId:org,input:{revision:1,limits:{monthlyCredits:null},reason:'Follow plan'},operator});const row=await latestOrganizationPolicy(db,org);assert.equal(row.limits.monthlyCredits,undefined);assert.equal(row.limits.maxUsers,3);});
test('cannot lower seats below members plus live invitations; platform authentication is required',async()=>{const{db}=fixture();await assert.rejects(saveOrganizationPolicy({prisma:db,orgId:org,input:{revision:0,limits:{maxUsers:1},reason:'Too small'},operator}),/2 members/);await assert.rejects(saveOrganizationPolicy({prisma:db,orgId:org,input:{revision:0,reason:'Unauthorized'},operator:null}),e=>e.status===401);});
test('organization administrators and arbitrary body scopes cannot access platform settings',async()=>{let called=false;for(const role of ['owner','admin','member']){const result=[];assert.equal(await handleOrganizationSettings({req:{method:'PATCH',session:{role,orgId:org}},res:{},pathname:`/admin/api/platform/organizations/${other}/settings`,prisma:{},getPlatformAdminSession:()=>null,parseBody:()=>{called=true;},jsonResponse:(_r,body,status)=>result.push({body,status})}),true);assert.equal(result[0].status,401);}assert.equal(called,false);});
test('authorized platform save returns persisted scoped settings and records operator audit',async()=>{const{db}=fixture(),responses=[],audits=[];await handleOrganizationSettings({req:{method:'PATCH'},res:{},pathname:`/admin/api/platform/organizations/${org}/settings`,prisma:db,getPlatformAdminSession:()=>operator,parseBody:async()=>({revision:0,limits:{monthlyCredits:500,maxUsers:3},reason:'Company capacity'}),jsonResponse:(_r,body,status=200)=>responses.push({body,status}),resolvePlan:async()=>({plan:materializeOrganizationPolicy(getPlan('free'),await latestOrganizationPolicy(db,org)),entitlement:null}),creditService:{getSummary:async()=>({included:500,used:20,reserved:5,remaining:475})},usageTracker:{getUsage:async()=>({})},audit:async entry=>audits.push(entry)});assert.equal(responses[0].status,200);assert.equal(responses[0].body.settings.revision,1);assert.equal(responses[0].body.settings.usage.credits.used,20);assert.equal(audits[0].organizationId,org);assert.equal(audits[0].sessionId,operator.sessionId);assert.equal(await latestOrganizationPolicy(db,other),null);});
test('settings read returns current effective values and historical credit usage',async()=>{const{db}=fixture();await saveOrganizationPolicy({prisma:db,orgId:org,input:{revision:0,limits:{monthlyCredits:3000,maxUsers:3},reason:'Pilot capacity'},operator});const result=await readOrganizationSettings({prisma:db,orgId:org,resolvePlan:async()=>({plan:materializeOrganizationPolicy(getPlan('free'),await latestOrganizationPolicy(db,org)),entitlement:null}),creditService:{getSummary:async()=>({included:3000,used:400,reserved:10,remaining:2590})},usageTracker:{getUsage:async()=>({searchQueries:10})}});assert.equal(result.revision,1);assert.equal(result.usage.seats,2);assert.equal(result.usage.credits.used,400);assert.equal(result.effective.limits.maxUsers,3);});
test('zero quota denies new seats, searches and connector use',async()=>{const plan=materializeOrganizationPolicy(getPlan('free'),{limits:{maxUsers:0,maxConnectors:0,searchQueriesPerMonth:0}}),db={userOrganization:{count:async()=>0},platformIntegration:{count:async()=>0}};const enforcer=new PlanEnforcer(db,{getOrgPlan:async()=>plan},{getUsage:async()=>({}),getDailySnapshot:async()=>({})});for(const type of ['users','searches','connectors'])assert.equal((await enforcer.checkLimit(org,type,1)).allowed,false);});
test('credit service computes remaining from allowance and existing usage, including reservations',async()=>{const plan=materializeOrganizationPolicy(getPlan('free'),{limits:{monthlyCredits:100}});const db={$queryRawUnsafe:async sql=>sql.includes('GROUP BY state')?[{state:'reserved',quantity:'10'}]:sql.includes('GROUP BY 1')?[{service:'composio_tool_call',quantity:'25',units:'25'}]:sql.includes('FROM "OrgUsage"')?[]:[{seconds:'0'}]};const credit=new CreditService({prisma:db,planStore:{getOrgPlan:async()=>plan}});const summary=await credit.getSummary(org);assert.equal(summary.included,100);assert.equal(summary.used,25);assert.equal(summary.reserved,10);assert.equal(summary.remaining,65);});
test('storage read failures remain explicit rather than removing organization restrictions',async()=>{await assert.rejects(latestOrganizationPolicy({$queryRawUnsafe:async()=>{throw Error('offline');}},org),e=>e.code==='ORGANIZATION_POLICY_UNAVAILABLE'&&e.status===503);});

test('shared effective resolver applies persisted quotas and features only to the chosen organization',async()=>{const{db}=fixture();db.entitlementGrant={findFirst:async()=>null};db.organizationEntitlement={findFirst:async()=>null};db.planCatalogVersion={findFirst:async()=>null};await saveOrganizationPolicy({prisma:db,orgId:org,input:{revision:0,limits:{monthlyCredits:3000},features:{cognitiveDreaming:true},reason:'Company allowance'},operator});const resolved=await getEffectivePlan(db,org),untouched=await getEffectivePlan(db,other);assert.equal(resolved.plan.limits.monthlyCredits,3000);assert.equal(resolved.plan.features.cognitiveDreaming,true);assert.equal(untouched.plan.limits.monthlyCredits,getPlan('free').limits.monthlyCredits);db.entitlementGrant.findFirst=async()=>({id:org,status:'suspended',source:'enterprise_invitation',startsAt:new Date()});db.entitlementVersion={findFirst:async()=>null};const suspended=await getEffectivePlan(db,org);assert.equal(suspended.plan.organizationPolicySuspended,true);assert.equal(suspended.plan.features.cognitiveDreaming,false);assert.equal(suspended.entitlement.status,'suspended');});
