import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {resolveNativeSlackSource,nativeSlackSender,admitNativeSlackSignal,verifyDreamSignalToken,admitDreamSignal} from '../../src/connectors/runtime-signal-hub.js';
const org='8cf195d6-f2c8-453a-bd95-b8a3d70bf0b0',user='85601c95-b367-45b4-b66b-069b68c4dfd0';
function fixture(){const writes=[],calls=[];let rows=[{id:'0a1da843-1fe2-492e-aa70-e7de5e1f096e',userId:user,connectorMetadata:{attention_org_id:org,attention_enabled_at:'2024-01-01T00:00:00Z',provider_metadata:{team_id:'TABC'}}}];const db={platformIntegration:{findMany:async()=>rows},userOrganization:{findUnique:async()=>({role:'admin',isActive:true})},user:{findUnique:async()=>({deletedAt:null})},$executeRawUnsafe:async(...args)=>{writes.push(args);return 1},$queryRawUnsafe:async(sql,...args)=>sql.includes('SELECT id,status')?[{id:args[0],status:'active',runtime_attention:true}]:[]};return {db,writes,calls,setRows:v=>rows=v,classify:c=>calls.push(c)}}
test('only exact workspace mapping and explicit org binding enter attention',async()=>{const f=fixture(),payload={team_id:'TABC',event_id:'Ev1',event:{type:'message',text:'Check S3',channel:'CABC',user:'UEXT',ts:'1720000000'}};const source=await resolveNativeSlackSource(f.db,payload);const result=await admitNativeSlackSignal(f.db,payload,source,f.classify);assert.equal(result.accepted,true);assert.equal(f.calls.length,1);assert.deepEqual(f.calls[0].allowedAccountIds,['native:slack:'+source.connection.id]);const insert=f.writes.find(w=>w[0].includes('INSERT INTO hivemind_trigger_events'));assert.equal(JSON.parse(insert[5]).user,'UEXT');assert.equal(JSON.parse(insert[5])._hivemind.source_is_untrusted,true);f.setRows([]);await assert.rejects(resolveNativeSlackSource(f.db,payload),/ambiguous/);f.setRows([source.connection,source.connection]);await assert.rejects(resolveNativeSlackSource(f.db,payload),/ambiguous/)});
test('unbound and unsupported events cannot trigger work',async()=>{const f=fixture();const source={orgId:null,connection:{userId:user,connectorMetadata:{attention_enabled_at:'2024-01-01T00:00:00Z'}},accountId:'native:slack:id'};assert.equal((await admitNativeSlackSignal(f.db,{event:{}},source,f.classify)).quiet,'org_binding_required');assert.equal(f.calls.length,0);source.orgId=org;assert.equal((await admitNativeSlackSignal(f.db,{event_id:'id',event:{type:'unknown_event',text:'wake',channel:'C'}},source,f.classify)).quiet,'unsupported_or_noise');assert.equal(f.writes.length,0)});
test('inactive and non-admin source owners are rejected',async()=>{const f=fixture();f.db.userOrganization.findUnique=async()=>({role:'member',isActive:true});await assert.rejects(resolveNativeSlackSource(f.db,{team_id:'TABC'}),/admin_required/);f.db.userOrganization.findUnique=async()=>({role:'admin',isActive:false});await assert.rejects(resolveNativeSlackSource(f.db,{team_id:'TABC'}),/admin_required/)});
test('dream callback is body-scoped, bounded and purpose-separated',()=>{const input={source:'dreaming',orgId:org,userId:user,runId:org};const secret='x'.repeat(32),at=Math.floor(Date.now()/1000);const encode=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const raw=encode({alg:'HS256'})+'.'+encode({iss:'hivemind-dreamer',aud:'hivemind-attention-signals',sub:user,org_id:org,run_id:org,iat:at,exp:at+30,jti:'unique'});const token=raw+'.'+createHmac('sha256',secret).update(raw).digest('base64url');verifyDreamSignalToken(token,input,secret);assert.throws(()=>verifyDreamSignalToken(token,{...input,userId:org},secret),/invalid/);assert.throws(()=>verifyDreamSignalToken(token,input,secret,(at+31)*1000),/invalid/)});
test('dream source loads only persisted eligible output receipts',async()=>{const f=fixture();f.db.harnessDreamRun={findUnique:async()=>({id:org,orgId:org,userId:user,status:'completed',revision:1,triggerId:'scheduled',outputs:[{idempotencyKey:'one',memoryId:user,receipt:{id:user},memory:{orgId:org,scope:'organization',title:'Finding',content:'Evidence',tags:['flashback'],createdAt:new Date()}}]})};f.db.harnessDreamSettings={findUnique:async()=>({enabled:true,userId:user,revision:1})};const result=await admitDreamSignal(f.db,{source:'dreaming',runId:org,orgId:org,userId:user},f.classify,{HIVEMIND_NATIVE_SIGNAL_ADMIT_AFTER:'2024-01-01T00:00:00Z'});assert.equal(result.outputs,1);assert.equal(f.calls.length,1);f.db.harnessDreamSettings.findUnique=async()=>({enabled:false});assert.equal((await admitDreamSignal(f.db,{source:'dreaming',runId:org,orgId:org,userId:user},f.classify,{HIVEMIND_NATIVE_SIGNAL_ADMIT_AFTER:'2024-01-01T00:00:00Z'})).quiet,'dream_not_admitted')});

test('dream findings require existing organization or active org-visible project semantics',async()=>{const f=fixture();let memory={orgId:org,scope:'project',projectId:user,tags:['flashback'],createdAt:new Date()};f.db.harnessDreamRun={findUnique:async()=>({id:org,orgId:org,userId:user,status:'completed',revision:1,triggerId:'scheduled',outputs:[{idempotencyKey:'project',memoryId:user,receipt:{id:user},memory}]})};f.db.harnessDreamSettings={findUnique:async()=>({enabled:true,userId:user,revision:1})};f.db.project={findFirst:async()=>null};const input={source:'dreaming',runId:org,orgId:org,userId:user},env={HIVEMIND_NATIVE_SIGNAL_ADMIT_AFTER:'2024-01-01T00:00:00Z'};assert.equal((await admitDreamSignal(f.db,input,f.classify,env)).outputs,0);f.db.project.findFirst=async()=>({id:user});assert.equal((await admitDreamSignal(f.db,input,f.classify,env)).outputs,1);memory.scope='personal';assert.equal((await admitDreamSignal(f.db,input,f.classify,env)).outputs,0)});

test('only an exact OAuth subject maps a Slack author to an authenticated admin',async()=>{
 const f=fixture(),source=await resolveNativeSlackSource(f.db,{team_id:'TABC'});
 source.connection.connectorMetadata.provider_metadata.authed_user_id='UADMIN';
 assert.equal((await nativeSlackSender(f.db,source,{user:'OTHER'})).verified,false);
 assert.equal((await nativeSlackSender(f.db,source,{user:'UADMIN',bot_id:'B'})).verified,false);
 const sender=await nativeSlackSender(f.db,source,{user:'UADMIN'});assert.equal(sender.verified,true);assert.equal(sender.userId,user);assert.equal(sender.orgId,org);
 f.db.userOrganization.findUnique=async()=>({role:'member',isActive:true});assert.equal((await nativeSlackSender(f.db,source,{user:'UADMIN'})).verified,false);
});
