#!/usr/bin/env bash
#
# publish-byod.sh — republish the byod/ directory to the `byod` setup branch.
#
# The `byod` branch is what fresh self-host installs clone:
#     git clone --branch byod --single-branch <repo> hivemind-byod && ./setup.sh
# Its ROOT is a mirror of byod/ on the main line (byod/agent/server.mjs becomes
# agent/server.mjs, etc.). byod/ is the SOURCE OF TRUTH; this republishes it.
#
# Idempotent: if the branch already matches byod/, it pushes nothing. Uses an
# isolated worktree, so it never disturbs the current working tree.
#
# Runs locally (`make publish-byod`) and in CI (.github/workflows/byod-publish.yml).
set -euo pipefail

BRANCH=byod
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

TMP="$(mktemp -d)"
WT="$TMP/byod-wt"
STAGED="$TMP/byod-bundle"
cleanup() {
  git worktree remove --force "$WT" >/dev/null 2>&1 || true
  rm -rf "$TMP"
}
trap cleanup EXIT

git fetch -q origin "$BRANCH"
git worktree add -q --force "$WT" "origin/$BRANCH"
( cd "$WT" && git checkout -q -B "$BRANCH" "origin/$BRANCH" )

# Build the branch through the same staging contract used by the sync checker.
"$ROOT/scripts/stage-byod-bundle.sh" "$ROOT" "$STAGED"

# The isolated worktree contains no customer runtime state, so every unexpected
# tracked branch file can and must be removed. Only Git's own metadata is exempt.
rsync -a --delete --exclude='.git' "$STAGED/" "$WT/"

cd "$WT"
if [ -z "$(git status --porcelain)" ]; then
  echo "✅ byod branch already in sync — nothing to publish."
  exit 0
fi

# Use ambient git identity; fall back to a bot identity in CI where none is set.
if [ -z "$(git config user.email || true)" ]; then
  git config user.email "github-actions[bot]@users.noreply.github.com"
  git config user.name  "github-actions[bot]"
fi

SRC_SHA="$(cd "$ROOT" && git rev-parse --short HEAD)"
git add -A
git commit -q -m "sync(byod): republish byod/ from ${SRC_SHA}

Auto-generated by scripts/publish-byod.sh. Source of truth: byod/ on the main line.
Do not edit this branch by hand — changes will be overwritten on the next publish."
git push -q origin "HEAD:$BRANCH"
echo "✅ Published byod/ → byod branch ($(git rev-parse --short HEAD))."
