#!/usr/bin/env bash
#
# publish-byod.sh — republish the byod/ directory to the `byod` setup branch.
#
# The `byod` branch is what fresh self-host installs clone:
#     git clone --branch byod --single-branch <repo> hivemind-byod && ./setup.sh
# Its ROOT is a mirror of byod/ on the main line (byod/agent/server.mjs becomes
# agent/server.mjs, etc.). byod/ is the SOURCE OF TRUTH; this republishes it.
#
# Idempotent: if the branch already matches byod/, it pushes nothing. Uses an
# isolated worktree, so it never disturbs the current working tree.
#
# Runs locally (`make publish-byod`) and in CI (.github/workflows/byod-publish.yml).
set -euo pipefail

BRANCH=byod
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

WT="$(mktemp -d)/byod-wt"
cleanup() { git worktree remove --force "$WT" >/dev/null 2>&1 || true; }
trap cleanup EXIT

git fetch -q origin "$BRANCH"
git worktree add -q --force "$WT" "origin/$BRANCH"
( cd "$WT" && git checkout -q -B "$BRANCH" "origin/$BRANCH" )

# Mirror byod/ → branch root. --delete keeps it EXACT (drops files removed from
# byod/). Excludes are protected from deletion too.
rsync -a --delete \
  --exclude='.git' --exclude='node_modules' --exclude='data' \
  --exclude='.byod-warm.log' --exclude='.env' \
  "$ROOT/byod/" "$WT/"

# backup.sh and doctor.sh are shipped as standalone customer commands. Keep the
# manifest implementation single-sourced on main, but include it in the
# generated BYOD branch where repository-level ../scripts does not exist.
install -m 0755 "$ROOT/scripts/storage-manifest.mjs" "$WT/storage-manifest.mjs"
install -m 0755 "$ROOT/scripts/storage-restore-drill.sh" "$WT/storage-restore-drill.sh"

cd "$WT"
if [ -z "$(git status --porcelain)" ]; then
  echo "✅ byod branch already in sync — nothing to publish."
  exit 0
fi

# Use ambient git identity; fall back to a bot identity in CI where none is set.
if [ -z "$(git config user.email || true)" ]; then
  git config user.email "github-actions[bot]@users.noreply.github.com"
  git config user.name  "github-actions[bot]"
fi

SRC_SHA="$(cd "$ROOT" && git rev-parse --short HEAD)"
git add -A
git commit -q -m "sync(byod): republish byod/ from ${SRC_SHA}

Auto-generated by scripts/publish-byod.sh. Source of truth: byod/ on the main line.
Do not edit this branch by hand — changes will be overwritten on the next publish."
git push -q origin "HEAD:$BRANCH"
echo "✅ Published byod/ → byod branch ($(git rev-parse --short HEAD))."
