import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from 'cloudflare:workers';
import { NonRetryableError } from 'cloudflare:workflows';

type Trigger = { org_id: string; trigger: 'dirty'|'idle'|'scheduled'|'manual'|'recovery'; trigger_id: string; requested_at: string; pipeline_version: 2 };
type Flags = Record<string, boolean>;
type Env = { DREAM_WORKFLOW: Workflow<Trigger & { flags: Flags; flag_details: unknown; model_route?: string }>; DREAM_TRIGGER_QUEUE: Queue<Trigger>; DREAM_ARTIFACTS: R2Bucket; FLAGS: Flagship; HIVEMIND_DREAM_API_URL: string; HIVEMIND_DREAM_WORKFLOW_SECRET: string; HIVEMIND_DREAM_INSTANCE_PREFIX?: string };
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const FLAG_NAMES=['dream_workflow_v2','dream_entity_walk_v1','dream_temporal_walk_v1','dream_causal_walk_v1','dream_verified_derivations_v1','dream_subject_profiles_v1','dream_reconsolidation_v1','dream_ui_insights_v1'] as const;
const STAGES=['admit','select-subjects','walk-graph','generate-candidates','verify-candidates','persist-cognition','project-derivations','update-profiles','embed','reconcile','publish','finalize'] as const;

function valid(v: unknown): v is Trigger { const p=v as Trigger; return !!p&&UUID.test(String(p.org_id||''))&&['dirty','idle','scheduled','manual','recovery'].includes(p.trigger)&&!!p.trigger_id&&Number.isFinite(Date.parse(p.requested_at))&&p.pipeline_version===2; }
function auth(req: Request,env:Env){return !!env.HIVEMIND_DREAM_WORKFLOW_SECRET&&req.headers.get('authorization')===`Bearer ${env.HIVEMIND_DREAM_WORKFLOW_SECRET}`;}
function instanceId(env:Env,p:Trigger){const prefix=String(env.HIVEMIND_DREAM_INSTANCE_PREFIX||'dream').replace(/[^a-z0-9-]/gi,'').slice(0,18);const epoch=String(p.trigger_id).replace(/[^a-z0-9-]/gi,'-').slice(0,32);return `${prefix}-${p.org_id}-${epoch}-v2`.slice(0,100);}
async function flags(env:Env,org:string){const values:Flags={};const details:Record<string,unknown>={};for(const name of FLAG_NAMES){try{const d=await env.FLAGS.getBooleanDetails(name,false,{targetingKey:org,org_id:org});values[name]=d.value===true;details[name]={value:d.value,variant:d.variant,reason:d.reason,error_code:d.errorCode};}catch(error){values[name]=false;details[name]={value:false,reason:'evaluation_error',error:String(error)};}}return {values,details};}
async function api<T=Record<string,unknown>>(env:Env,path:string,body:unknown):Promise<T>{const r=await fetch(`${env.HIVEMIND_DREAM_API_URL.replace(/\/$/,'')}${path}`,{method:'POST',headers:{authorization:`Bearer ${env.HIVEMIND_DREAM_WORKFLOW_SECRET}`,'content-type':'application/json'},body:JSON.stringify(body)});const p:Record<string,unknown>=await r.json<Record<string,unknown>>().catch(()=>({}));if(!r.ok){const m=String(p.error||`dream_api_${r.status}`);if([400,401,403,404,409,422].includes(r.status)||p.retryable===false)throw new NonRetryableError(m);throw new Error(m);}return p as T;}
async function enqueue(env:Env,p:Trigger){if(!valid(p))throw new NonRetryableError('invalid_trigger');await env.DREAM_TRIGGER_QUEUE.send(p);return {ok:true,queued:true,trigger_id:p.trigger_id};}

export class DreamWorkflow extends WorkflowEntrypoint<Env,Trigger & {flags:Flags;flag_details:unknown;model_route?:string}>{async run(event:WorkflowEvent<Trigger & {flags:Flags;flag_details:unknown;model_route?:string}>,step:WorkflowStep){const p=event.payload;if(!valid(p)||p.flags.dream_workflow_v2!==true)throw new NonRetryableError('dream_feature_disabled');let receipt:Record<string,any>={};let currentStage='admit';try{for(const stage of STAGES){currentStage=stage;if(stage==='publish'){const current=await flags(this.env,p.org_id);if(!current.values.dream_workflow_v2)throw new NonRetryableError('dream_kill_switch_disabled');}receipt=await step.do<Record<string,any>>(stage,{retries:{limit:8,delay:'15 seconds',backoff:'exponential'},timeout:'15 minutes'},()=>api<Record<string,any>>(this.env,stage==='admit'?'/internal/dream/admit':'/internal/dream/stage',stage==='admit'?{...p,trigger_key:p.trigger_id,workflow_instance_id:event.instanceId}:{run_id:receipt.run_id,stage,pipeline_version:2}));if(receipt.status==='error'||receipt.status==='cancelled')throw new NonRetryableError(`dream_run_${receipt.status}`);}return receipt;}catch(error){if(receipt.run_id){const raw=error instanceof Error?error.message:'workflow_retry_exhausted';const failureCode=/^[a-z0-9_-]{1,160}$/i.test(raw)?raw:'workflow_stage_failed';await step.do<Record<string,any>>('record-terminal-failure',{retries:{limit:5,delay:'15 seconds',backoff:'exponential'},timeout:'2 minutes'},()=>api<Record<string,any>>(this.env,'/internal/dream/fail',{run_id:receipt.run_id,failed_stage:currentStage,failure_code:failureCode,pipeline_version:2}));}throw error;}}}

export default {
 async fetch(req:Request,env:Env){if(!auth(req,env))return Response.json({error:'Unauthorized'},{status:401});const u=new URL(req.url);if(req.method==='POST'&&u.pathname==='/start'){const p=await req.json<Trigger>().catch(()=>null);if(!valid(p))return Response.json({error:'invalid_trigger'},{status:400});await enqueue(env,p);return Response.json({ok:true,queued:true,trigger_id:p.trigger_id},{status:202});}if(req.method==='GET'&&u.pathname==='/status'){const id=u.searchParams.get('instance_id');if(!id)return Response.json({error:'instance_id_required'},{status:400});const i=await env.DREAM_WORKFLOW.get(id);return Response.json({instance_id:id,status:await i.status()});}return Response.json({error:'Not found'},{status:404});},
 async queue(batch:MessageBatch<Trigger>,env:Env){for(const m of batch.messages){try{if(!valid(m.body))throw new NonRetryableError('invalid_trigger');const f=await flags(env,m.body.org_id);if(!f.values.dream_workflow_v2)throw new NonRetryableError('dream_feature_disabled');const params={...m.body,flags:f.values,flag_details:f.details};const id=instanceId(env,m.body);try{await env.DREAM_WORKFLOW.create({id,params,retention:{successRetention:'30 days',errorRetention:'30 days'}});}catch{const i=await env.DREAM_WORKFLOW.get(id);const s=await i.status();if(s.status==='errored'||s.status==='terminated')await i.restart();}m.ack();}catch(error){if(error instanceof NonRetryableError){console.error(JSON.stringify({event:'dream_trigger_permanent_failure',error:String(error)}));m.ack();}else m.retry();}}},
 async scheduled(_c:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil((async()=>{const r=await api<{tenants:Trigger[]}>(env,'/internal/dream/eligible',{limit:100,now:new Date().toISOString()});for(const p of r.tenants||[])await enqueue(env,p);})());}
} satisfies ExportedHandler<Env,Trigger>;
